# Generated by Django 3.2 on 2022-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='topic',
            field=models.CharField(choices=[('', 'Select Topic *'), ('OR', 'Your Order'), ('PR', 'Jewellery Product'), ('DS', 'Jewellery Designer'), ('WB', 'Our Website'), ('OT', 'Other')], max_length=2),
        ),
    ]
