# Generated by Django 3.2 on 2022-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('', 'Select Category *'), ('OR', 'Orders'), ('DE', 'Deliveries'), ('PR', 'Products'), ('DS', 'Designers'), ('WB', 'Customer Accounts'), ('OT', 'Other')], default='OT', max_length=2),
            preserve_default=False,
        ),
    ]
