# Generated by Django 3.2 on 2022-01-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_designer_programmatic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='programmatic_name',
            field=models.CharField(editable=False, max_length=254),
        ),
    ]
