# Generated by Django 3.2 on 2022-01-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_alter_designer_programmatic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
