# Generated by Django 3.2 on 2022-01-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_designer_twitter_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='designers.designer'),
        ),
    ]
