# Generated by Django 3.2 on 2022-01-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_alter_collection_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='designers.designer'),
        ),
    ]
