# Generated by Django 3.2 on 2022-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='homepage_featured',
            field=models.BooleanField(default=False),
        ),
    ]
