# Generated by Django 3.2 on 2022-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_num_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_available',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
